import type { ScannedPage } from "../core/scanner.js";
import { detectKeyPages } from "./key-pages.js";
import {
  extractContractAddresses,
  extractCodeBlocks,
  extractTables,
  extractLinks,
  deduplicateBlocks,
  type ExtractedLink,
} from "./extractors.js";

export interface AiContextConfig {
  title: string;
  description: string;
  aiContextConfig?: {
    key_pages?: Array<{ path: string; section: string }>;
    extra_sections?: Array<{ title: string; content: string }>;
  };
}

const NETWORK_PATTERNS = [/chain\s*id/i, /rpc\s*(url|endpoint)/i];
const QUICKSTART_PATH_KEYWORDS = [
  "getting-started",
  "quickstart",
  "quick-start",
  "setup",
  "install",
  "sdk",
];

export function generateAiContext(
  pages: ScannedPage[],
  config: AiContextConfig,
): string {
  const keyPages = resolveKeyPages(pages, config);
  const sections: string[] = [];

  // Header
  sections.push(
    "<!-- Auto-generated by docs-ready. Review and customize. -->",
  );
  sections.push("");
  sections.push(`# ${config.title} — AI Context`);

  // Overview — always present
  sections.push("");
  sections.push("## Overview");
  sections.push("");
  sections.push(config.description);

  // Network Configuration
  const networkSection = buildNetworkSection(keyPages);
  if (networkSection) {
    sections.push("");
    sections.push("## Network Configuration");
    sections.push("");
    sections.push(networkSection);
  }

  // Contract Addresses
  const contractSection = buildContractSection(keyPages);
  if (contractSection) {
    sections.push("");
    sections.push("## Contract Addresses");
    sections.push("");
    sections.push(contractSection);
  }

  // Quick Start
  const quickStartSection = buildQuickStartSection(keyPages);
  if (quickStartSection) {
    sections.push("");
    sections.push("## Quick Start");
    sections.push("");
    sections.push(quickStartSection);
  }

  // Links & Resources
  const linksSection = buildLinksSection(keyPages);
  if (linksSection) {
    sections.push("");
    sections.push("## Links & Resources");
    sections.push("");
    sections.push(linksSection);
  }

  // Extra sections from config
  if (config.aiContextConfig?.extra_sections) {
    for (const extra of config.aiContextConfig.extra_sections) {
      sections.push("");
      sections.push(`## ${extra.title}`);
      sections.push("");
      sections.push(extra.content);
    }
  }

  return sections.join("\n") + "\n";
}

function resolveKeyPages(
  pages: ScannedPage[],
  config: AiContextConfig,
): ScannedPage[] {
  // Manual override
  if (config.aiContextConfig?.key_pages?.length) {
    const manual: ScannedPage[] = [];
    for (const kp of config.aiContextConfig.key_pages) {
      const match = pages.find(
        (p) =>
          p.relativePath === kp.path ||
          p.relativePath === kp.path.replace(/\\/g, "/"),
      );
      if (match) {
        manual.push(match);
      }
    }
    // If manual pages resolved, return them; otherwise fall through
    if (manual.length > 0) {
      return manual;
    }
  }

  // Auto-detect
  const detected = detectKeyPages(pages);
  if (detected.length > 0) {
    return detected.map((d) => d.page);
  }

  // Fallback: all pages
  return pages;
}

function buildNetworkSection(pages: ScannedPage[]): string | null {
  const networkTables: string[] = [];

  for (const page of pages) {
    const hasNetworkContent = NETWORK_PATTERNS.some((p) =>
      p.test(page.content),
    );
    if (!hasNetworkContent) continue;

    const tables = extractTables(page.content);
    // Only include tables that contain network-related content
    for (const table of tables) {
      if (NETWORK_PATTERNS.some((p) => p.test(table))) {
        networkTables.push(`### ${page.title}\n\n${table}`);
      }
    }
  }

  if (networkTables.length === 0) return null;
  return networkTables.join("\n\n");
}

function buildContractSection(pages: ScannedPage[]): string | null {
  const addressTables: string[] = [];
  const looseAddresses: string[] = [];

  for (const page of pages) {
    const addresses = extractContractAddresses(page.content);
    if (addresses.length === 0) continue;

    // Check if the addresses appear inside tables
    const tables = extractTables(page.content);
    const tablesWithAddresses = tables.filter((t) =>
      addresses.some((addr) => t.includes(addr)),
    );

    if (tablesWithAddresses.length > 0) {
      for (const table of tablesWithAddresses) {
        addressTables.push(`### ${page.title}\n\n${table}`);
      }
    } else {
      // Fallback: bullet list
      for (const addr of addresses) {
        looseAddresses.push(`- \`${addr}\``);
      }
    }
  }

  if (addressTables.length === 0 && looseAddresses.length === 0) return null;

  const parts: string[] = [];
  if (addressTables.length > 0) {
    parts.push(addressTables.join("\n\n"));
  }
  if (looseAddresses.length > 0) {
    parts.push([...new Set(looseAddresses)].join("\n"));
  }
  return parts.join("\n\n");
}

function buildQuickStartSection(pages: ScannedPage[]): string | null {
  const allBlocks = new Map<string, string[]>();

  for (const page of pages) {
    const pathLower = page.relativePath.toLowerCase();
    const titleLower = page.title.toLowerCase();
    const isQuickstartPage =
      QUICKSTART_PATH_KEYWORDS.some((kw) => pathLower.includes(kw)) ||
      QUICKSTART_PATH_KEYWORDS.some((kw) => titleLower.includes(kw));

    if (!isQuickstartPage) continue;

    const blocks = extractCodeBlocks(page.content);
    for (const [lang, codeList] of blocks) {
      if (!allBlocks.has(lang)) {
        allBlocks.set(lang, []);
      }
      allBlocks.get(lang)!.push(...codeList);
    }
  }

  if (allBlocks.size === 0) return null;

  const deduplicated = deduplicateBlocks(allBlocks);
  const parts: string[] = [];

  for (const [lang, codeList] of deduplicated) {
    for (const code of codeList) {
      parts.push(`\`\`\`${lang}\n${code}\n\`\`\``);
    }
  }

  return parts.join("\n\n");
}

function buildLinksSection(pages: ScannedPage[]): string | null {
  const allLinks: ExtractedLink[] = [];

  for (const page of pages) {
    const links = extractLinks(page.content);
    allLinks.push(...links);
  }

  if (allLinks.length === 0) return null;

  // Deduplicate by URL
  const seen = new Set<string>();
  const unique: ExtractedLink[] = [];
  for (const link of allLinks) {
    if (!seen.has(link.url)) {
      seen.add(link.url);
      unique.push(link);
    }
  }

  // Categorize
  const github = unique.filter((l) => l.category === "github");
  const npm = unique.filter((l) => l.category === "npm");
  const external = unique.filter((l) => l.category === "external");

  const parts: string[] = [];

  if (github.length > 0) {
    parts.push("### GitHub");
    parts.push("");
    parts.push(...github.map((l) => `- [${l.text}](${l.url})`));
  }

  if (npm.length > 0) {
    parts.push("");
    parts.push("### npm");
    parts.push("");
    parts.push(...npm.map((l) => `- [${l.text}](${l.url})`));
  }

  if (external.length > 0) {
    parts.push("");
    parts.push("### External");
    parts.push("");
    parts.push(...external.map((l) => `- [${l.text}](${l.url})`));
  }

  return parts.join("\n");
}
