import fs from "node:fs/promises";
import path from "node:path";
import { createInterface } from "node:readline/promises";
import { stdin, stdout } from "node:process";
import { detectFramework } from "../../frameworks/detector.js";
import { log, spinner } from "../../utils/logger.js";

interface InitOptions {
  cwd?: string;
}

export async function initCommand(options: InitOptions = {}): Promise<void> {
  const cwd = options.cwd ?? process.cwd();
  const configPath = path.join(cwd, ".docs-ready.yaml");

  // Check if config already exists
  try {
    await fs.access(configPath);
    log.warn(".docs-ready.yaml already exists. Use --force to overwrite.");
    return;
  } catch {
    // Config doesn't exist, proceed
  }

  const spin = spinner("Detecting project structure...");
  spin.start();

  // Detect framework
  const framework = await detectFramework(cwd);
  spin.stop();

  log.info(`Detected framework: ${framework.name}`);
  log.info(`Docs directory: ${framework.docsDir}`);

  // Detect deployment platform
  const platform = await detectPlatform(cwd);
  if (platform !== "none") {
    log.info(`Detected platform: ${platform}`);
  }

  // Detect docusaurus-plugin-llms
  const hasLlmsPlugin = await detectLlmsPlugin(cwd);
  if (hasLlmsPlugin) {
    log.warn("Detected docusaurus-plugin-llms — disabling llms.txt/llms-full.txt generation.");
  }

  // Prompt for project info
  const rl = createInterface({ input: stdin, output: stdout });
  const title = await rl.question("Project title: ");
  const description = await rl.question("Description: ");
  const url = await rl.question("Docs URL (e.g. https://docs.example.com): ");
  rl.close();

  // Build config from inline template
  const rendered = buildConfig({
    title: title || "My Project",
    description: description || "Project documentation",
    url: url || "https://docs.example.com",
    docsDir: framework.docsDir,
    llmsTxt: !hasLlmsPlugin,
    llmsFullTxt: !hasLlmsPlugin,
    platform,
  });

  await fs.writeFile(configPath, rendered, "utf-8");
  log.success("Created .docs-ready.yaml");
  log.dim("Next: run `docs-ready generate` to create AI-facing files.");
}

interface ConfigTemplateData {
  title: string;
  description: string;
  url: string;
  docsDir: string;
  llmsTxt: boolean;
  llmsFullTxt: boolean;
  platform: string;
}

function buildConfig(data: ConfigTemplateData): string {
  return `# ============================================================
# docs-ready configuration
# Generated by \`docs-ready init\`
# Full reference: https://github.com/udhaykumarbala/docs-ready
# ============================================================

# --- Project metadata ---
title: "${data.title}"
description: "${data.description}"
url: "${data.url}"

# --- Documentation source ---
docs:
  dir: "${data.docsDir}"
  include:
    - "**/*.md"
    - "**/*.mdx"
  exclude:
    - "**/node_modules/**"
    - "**/_*"

# --- Generation ---
generate:
  llms_txt: ${data.llmsTxt}
  llms_full_txt: ${data.llmsFullTxt}
  ai_context: true
  output_dir: "./build"

# --- Deployment ---
deploy:
  platform: "${data.platform}"
`;
}

async function detectPlatform(
  cwd: string
): Promise<"vercel" | "netlify" | "cloudflare" | "none"> {
  const checks: Array<{ file: string; platform: "vercel" | "netlify" | "cloudflare" }> = [
    { file: "vercel.json", platform: "vercel" },
    { file: "netlify.toml", platform: "netlify" },
    { file: "_headers", platform: "cloudflare" },
    { file: "wrangler.toml", platform: "cloudflare" },
  ];

  for (const { file, platform } of checks) {
    try {
      await fs.access(path.join(cwd, file));
      return platform;
    } catch {
      // Not found, continue
    }
  }

  return "none";
}

async function detectLlmsPlugin(cwd: string): Promise<boolean> {
  try {
    const pkgPath = path.join(cwd, "package.json");
    const content = await fs.readFile(pkgPath, "utf-8");
    const pkg = JSON.parse(content);
    const allDeps = {
      ...pkg.dependencies,
      ...pkg.devDependencies,
    };
    return "docusaurus-plugin-llms" in allDeps;
  } catch {
    return false;
  }
}
