import type { DocsReadyConfig } from "../core/config.js";

export function generateWorkflowYaml(config: DocsReadyConfig): string {
  const schedule = config.guard.workflow.schedule;
  const labels = config.guard.workflow.labels.map((l) => `"${l}"`).join(", ");

  return `# Auto-generated by docs-ready. Safe to re-run.
name: docs-ready guard

on:
  schedule:
    - cron: "${schedule}"
  workflow_dispatch:

permissions:
  issues: write

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install docs-ready
        run: npm install -g docs-ready

      - name: Run guard checks
        id: guard
        run: |
          docs-ready guard --output markdown > guard-report.md 2>&1 || echo "GUARD_FAILED=true" >> $GITHUB_ENV

      - name: Close previous docs-ready issues
        if: env.GUARD_FAILED == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ${labels ? `[${labels}]` : '"docs-ready"'},
              state: "open",
            });
            for (const issue of issues.data) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: "closed",
              });
            }

      - name: Create issue on failure
        if: env.GUARD_FAILED == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require("fs");
            const body = fs.readFileSync("guard-report.md", "utf-8");
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "docs-ready: Guard checks failed",
              body: body,
              labels: [${labels}],
            });
`;
}
