import { describe, it, expect } from "vitest";
import { generateAiContext } from "../../src/generate/ai-context.js";
import { scanDocs } from "../../src/core/scanner.js";
import path from "node:path";

const OG_DOCS = path.resolve("tests/fixtures/0g-style-project/docs");
const DOCUSAURUS_DOCS = path.resolve("tests/fixtures/docusaurus-project/docs");

describe("generateAiContext", () => {
  it("renders all sections when content exists", async () => {
    const pages = await scanDocs(OG_DOCS, { include: ["**/*.md"], exclude: [] });
    const result = generateAiContext(pages, {
      title: "0G Documentation",
      description: "Decentralized AI operating system",
    });

    expect(result).toContain("<!-- Auto-generated by docs-ready. Review and customize. -->");
    expect(result).toContain("# 0G Documentation — AI Context");
    expect(result).toContain("## Network Configuration");
    expect(result).toContain("## Contract Addresses");
    expect(result).toContain("## Quick Start");
    expect(result).toContain("## Links & Resources");
  });

  it("omits empty sections", async () => {
    const pages = await scanDocs(DOCUSAURUS_DOCS, { include: ["**/*.md"], exclude: [] });
    const result = generateAiContext(pages, {
      title: "My Project",
      description: "A project",
    });

    // Docusaurus fixture has no contract addresses or network tables
    expect(result).not.toContain("## Contract Addresses");
    expect(result).not.toContain("## Network Configuration");
    // But should still have Quick Start (getting-started page has code blocks)
    expect(result).toContain("## Quick Start");
  });

  it("manual key_pages overrides auto-detection", async () => {
    const pages = await scanDocs(OG_DOCS, { include: ["**/*.md"], exclude: [] });
    const result = generateAiContext(pages, {
      title: "0G",
      description: "Test",
      aiContextConfig: {
        key_pages: [{ path: "sdk/typescript.md", section: "SDK" }],
      },
    });

    expect(result).toContain("npm install @0gfoundation/0g-ts-sdk");
  });

  it("extra_sections merge with auto-detected content", async () => {
    const pages = await scanDocs(OG_DOCS, { include: ["**/*.md"], exclude: [] });
    const result = generateAiContext(pages, {
      title: "0G",
      description: "Test",
      aiContextConfig: {
        extra_sections: [{ title: "Custom Section", content: "This is custom content." }],
      },
    });

    expect(result).toContain("## Custom Section");
    expect(result).toContain("This is custom content.");
    // Auto-detected content should still be there
    expect(result).toContain("## Network Configuration");
  });
});
